version: '3.8'
services:
  go:
    build: 
      context: .
      target: base
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - .:/go/src/project
    working_dir: /go/src/project
  grpcurl:
    image: fullstorydev/grpcurl:latest
